// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIBh_yyFx_atYH-UDoVssX-2L6s7OOVg8',
    appId: '1:158519996921:web:0bf8ec9f6d49706c7b0d28',
    messagingSenderId: '158519996921',
    projectId: 'tiktok-gt',
    authDomain: 'tiktok-gt.firebaseapp.com',
    storageBucket: 'tiktok-gt.appspot.com',
    measurementId: 'G-FTSP0VGE9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5O8yQIcRRk3Z7BsoYfCzF47xJw5sNO8Y',
    appId: '1:158519996921:android:7c998f7b89b1064a7b0d28',
    messagingSenderId: '158519996921',
    projectId: 'tiktok-gt',
    storageBucket: 'tiktok-gt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGwd6-ms2lX-rIt9_81iU2Yx9EZzVXEXw',
    appId: '1:158519996921:ios:8d0b3695d0de02117b0d28',
    messagingSenderId: '158519996921',
    projectId: 'tiktok-gt',
    storageBucket: 'tiktok-gt.appspot.com',
    iosBundleId: 'com.example.gyuteTiktokClone',
  );
}
